import fs from "fs/promises";
import path from "path";
import { fileURLToPath } from "url";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(scriptDir, "..");
const html = await fs.readFile(path.join(repoRoot, "src", "public", "index.html"), "utf8");
const styles = await fs.readFile(path.join(repoRoot, "src", "public", "styles.css"), "utf8");
const appJs = await fs.readFile(path.join(repoRoot, "src", "public", "app.js"), "utf8");

assertIncludes(html, [
  '<meta name="viewport" content="width=device-width, initial-scale=1">',
  "StockFlix Investor Studio",
  'data-view="portfolio"',
  'data-view="business"',
  'data-analysis-progress',
  'data-template-downloads',
  'Download watchlist guide template',
  '/api/analysis/template/portfolio',
  '/api/analysis/template/watchlist',
  'data-download-href="/api/analysis/template/portfolio"',
  'disabled>Sign in to analyze</button>',
  'Sign in before downloading templates, browsing files, or running analysis.',
  'aria-live="polite"',
  'data-frontend-version',
  'leftRailToggle',
  'Hide panel',
  '/styles.css?v=20260708-0830',
  '/app.js?v=20260708-0830',
], "HTML should expose viewport meta, brand, and primary dashboard navigation.");
if (html.includes('data-view="approvals"')) {
  throw new Error("Launch navigation should not expose deferred Approvals.");
}

assertIncludes(styles, [
  "overflow-x: hidden;",
  "max-width: 100%;",
  "overflow-wrap: anywhere;",
  "@media (max-width: 980px)",
  ".section-title",
  ".section-title > * + *",
  "align-content: start;",
  "align-self: start;",
  "@media (max-width: 640px)",
  ".view-grid button",
  ".analysis-status",
  ".analysis-links",
  ".analysis-details",
  ".app-shell.left-rail-collapsed",
  ".workspace-toggle",
  ".analysis-spinner",
  ".template-downloads",
  ".template-downloads.locked",
  ".download-link.disabled",
  ".frontend-version",
  ".reference-master-panel",
  ".reference-master-table input",
  ".reference-launch-evidence",
  ".evidence-marker-list",
  ".screener-beginner-guide",
  ".scatter-axis-summary",
  ".quadrant-zone",
  ".zone-dot",
  ".quadrant-guide",
  ".tooltip-trigger",
  ".tooltip-card",
  ".table-header-help",
  ".table-tooltip-card",
  ".simulation-growth-panel",
  ".simulation-chart-frame",
  ".chart-reading-guide",
  ".stock-chart-trigger",
  ".table-row-highlight",
  ".top-idea-point",
  ".sector-pro-panel",
  ".sector-beginner-summary",
  ".advanced-sector-details",
  ".sector-signal-grid",
  ".sector-signal-card",
  ".table-control-panel",
  ".field-picker-grid",
  ".table-control-status",
  ".portfolio-data-warning",
  ".think2-safety-summary",
  ".severity-badge",
  ".status-badge",
  ".table-warning-text",
  ".score-matrix-guide",
  ".score-matrix-cards",
  ".score-matrix-card",
  ".score-card-header",
  ".score-status",
  ".score-matrix-card .score-status-dot",
  ".score-matrix-card .score-status-green .score-status-dot",
  ".score-matrix-card .score-status-orange .score-status-dot",
  ".score-matrix-card .score-status-yellow .score-status-dot",
  ".score-matrix-card .score-status-red .score-status-dot",
  ".score-card-hint",
  ".plan-request-panel",
  ".compact-title",
  ".secondary-action",
  ".database-mode-advisor",
  ".mode-status",
  ".advisor-warning-list",
  ".production-environment-advisor",
  ".env-status",
  ".env-group-grid",
  ".system-admin-panel",
  ".admin-action-grid",
  ".business-section-tabs",
  ".user-management-panel",
  ".danger-action",
  "min-height: 44px;",
], "Stylesheet should include responsive viewport and tap-target safeguards.");

assertIncludes(styles, [
  "--red: #e50914",
  "grid-template-columns: minmax(300px, 380px) 1fr",
  "grid-template-columns: 1fr;",
  ".table-wrap",
  "overflow: auto;",
], "Stylesheet should keep desktop SaaS layout and table overflow guardrails.");

assertIncludes(appJs, [
  "renderBusinessView",
  "renderPortfolioView",
  "renderScreenerView",
  "renderSectorView",
  "renderSimulationView",
  "tableColumnTips",
  "data-table-header-hint",
  "ค่าที่น่าเริ่มดู",
  "Total_Score",
  "RRR",
  "Portfolio_Risk",
  "ops-alert-card",
  "renderLockedFeature",
  "data-upgrade-plan",
  "data-launch-plan-note",
  "data-manual-package-flow",
  "data-advisor-coming-soon",
  "data-deferred-upgrade-note",
  "starter_pro_manual_ready",
  "setAnalysisButtonLoading",
  "syncAnalysisAccess",
  "Sign in to analyze",
  "Create an account or sign in before downloading templates",
  "frontendBuildVersion",
  "20260708-0830",
  "Think2 Manual Plan Request v0.2.0",
  "codex/think2-safety-layer-planning@20260708-0830",
  "penthammachat",
  "/api/subscription/request",
  "/api/admin/plan-requests",
  "/cancel",
  "/reject",
  "requestPlan",
  "cancelPlanRequest",
  "rejectPlanRequest",
  "loadPlanRequests",
  "Waiting for admin approval",
  "Package request sent",
  "Cancel request",
  "data-plan-request-admin-panel",
  "data-approve-plan-request",
  "data-reject-plan-request",
  "data-cancel-plan-request",
  "subscription.plan_request_created",
  "subscription.plan_request_approved",
  "subscription.plan_request_rejected",
  "subscription.plan_request_canceled",
  "renderAnalysisResultSummary",
  "Processing details",
  "Ready ·",
  "stockflix.leftRailCollapsed",
  "left-rail-collapsed",
  "toggleLeftRail",
  "canRunPortfolioAnalysis",
  "analysisPackageRequiredMessage",
  "Portfolio analysis requires Starter or Pro",
  "package required",
  "Analyze clicks",
  "handleDelegatedAnalysisClick",
  "pointerup",
  "updateFrontendDiagnostics",
  "Frontend version",
  "getAnalysisSelectedFiles",
  "handleAnalysisButtonClick",
  "Preparing your upload...",
  "isAttachedUploadFile",
  "formData = new FormData(analysisForm);",
  "The selected files could not be attached",
  "The browser could not prepare the upload",
  "renderUploadSummaryMessages",
  "Read portfolio file",
  "Combined unique symbols sent to market data",
  "startAnalysisProgressTimers",
  "Analyzing your portfolio",
  "data-recommended-actions-controls",
  "data-recommended-field-picker",
  "data-recommended-action-filter",
  "data-recommended-sector-filter",
  "data-recommended-score-band",
  "attachPortfolioVisualFilters",
  "data-sector-exposure-complete",
  "ไม่มีการรวมเป็น Other",
  "recommendedActionFields",
  "attachRecommendedActionsControls",
  "data-portfolio-data-warning",
  "data-portfolio-empty-holdings",
  "latest analysis has",
  "Market data was unavailable in the last run.",
  "Data_Status",
  "Data_Warnings",
  "Conflict_Severity",
  "Conflict_Alerts",
  "Quality_Score",
  "Valuation_Score",
  "Setup_Score",
  "Balance_Risk_Score",
  "Liquidity_Score",
  "Composite_Score_v2",
  "Composite Score v2",
  "Technical_RRR",
  "Fundamental_RRR",
  "Fundamental_RRR_Status",
  "Fundamental_RRR_Note",
  "Fundamental RRR Status",
  "INSUFFICIENT_DATA",
  "Action_v2_Shadow",
  "Action_v2_Confidence",
  "Action_v2_Risk_Block",
  "Action_v2_Change",
  "Action_v2_Rationale",
  "Action v2 Shadow",
  "Decision_Engine_Mode",
  "Effective_Target_Action",
  "Effective_Action_Source",
  "Decision Engine Mode",
  "Effective Target Action",
  "data-score-matrix-guide",
  "Score matrix แบบอ่านง่าย",
  "scoreStatusForValue",
  "75+ ดี",
  "ค่อนข้างดี",
  "ควรระวัง",
  "ไม่ได้แทน Total Score หรือ Target Action",
  "data-think2-safety-summary",
  "Safety check before acting",
  "severity-badge",
  "status-badge",
  "Conflict Severity",
  "Conflict Alerts",
  "Order by",
  "data-screener-beginner-guidance",
  "data-screener-strict-defaults",
  "data-screener-symbol-search",
  "data-screener-default-score",
  "data-screener-default-rrr",
  "data-screener-default-de",
  "data-screener-quadrant-guide",
  "data-chart-filter-context",
  "scoreThreshold",
  "rrrThreshold",
  "Score ${formatNumber(scoreThreshold)}+",
  "RRR ${formatNumber(rrrThreshold)}+",
  "quadrant-zone-best",
  "zone-dot zone-best",
  "ขวาบน",
  "beginner defaults",
  "data-screener-tooltip",
  "data-portfolio-quick-guidance",
  "data-stock-highlight",
  "data-stock-row",
  "table-row-highlight",
  "attachStockHighlightControls",
  "top-idea-point",
  "data-simulation-buy-mode",
  "data-simulation-split-input",
  "data-simulation-buy-plan",
  "data-simulation-growth-chart",
  "data-simulation-chart-guide",
  "strategy-line",
  "buy-hold-line",
  "Portfolio Growth: Strategy vs Buy & Hold",
  "วิธีอ่านกราฟนี้",
  "Split Buy",
  "data-sector-pro-intelligence",
  "data-sector-default-all",
  "All sectors overview",
  "ค่าเริ่มต้นแสดงทุกหุ้นในทุก sector",
  "data-sector-beginner-summary",
  "data-sector-score-filter",
  "data-sector-price-position-filter",
  "pricePositionThreshold",
  "zoneClasses",
  "topLeft: \"best\"",
  "topRight: \"watch\"",
  "Price position line",
  "data-sector-chart-filter-context",
  "data-sector-chart-guide",
  "data-sector-advanced-table",
  "data-sector-ranking-panel",
  "data-sector-risk-panel",
  "data-sector-rotation-panel",
  "กลุ่มไหนน่าศึกษา",
  "พอร์ตกระจุกตรงไหน",
  "สัญญาณกลุ่มแบบอ่านง่าย",
  "ดูตารางตัวเลขขั้นสูง",
  "Score 60+",
  "RRR 1.5+",
  "D/E <= 1.0",
  "renderReferenceMasterReview",
  "data-reference-master-launch-evidence",
  "renderDatabaseModeAdvisor",
  "data-database-mode-advisor",
  "Database mode advisor",
  "data-database-mode-commands",
  "renderProductionEnvironmentAdvisor",
  "data-production-environment-advisor",
  "Production environment advisor",
  "data-production-env-commands",
  "Portfolio Data Health",
  "System Admin",
  "data-business-admin-cockpit",
  "data-business-section-tabs",
  "data-business-section-default",
  "Member Management",
  "data-member-management-focus",
  "data-business-advanced-ops",
  "data-member-management-row",
  "data-system-admin-panel",
  "data-system-admin-actions",
  "User Management",
  "data-user-management-panel",
  "data-admin-package-management",
  "data-subscription-user",
  "data-save-subscription",
  "data-delete-user",
  "deleteManagedUser",
  "Delete user",
  "Waiting admin",
  "manual package update",
  "team.subscription_update",
  "team.user_deleted",
  "data-portfolio-health-controls",
  "data-portfolio-health-filter",
  "attachPortfolioHealthControls",
  "filterPortfolioHealthSnapshots",
  "saveReferenceMasterRecord",
  "reference_master.review",
], "Frontend bundle should keep key authenticated and entitlement-gated views.");

assertBefore(appJs, "const recommendedActionFields", "await initialize();", "Recommended action fields must initialize before the app can render a saved portfolio.");
assertBefore(appJs, "const recommendedActionSortFields", "await initialize();", "Recommended action sort fields must initialize before the app can render a saved portfolio.");
assertBefore(appJs, "const tableColumnTips", "await initialize();", "Table header hints must initialize before saved portfolio or active views render tables.");
assertBefore(appJs, "const screenerFilterTips", "await initialize();", "Screener tooltip tips must initialize before the app can render a saved Screener view.");
assertBefore(appJs, "formData = new FormData(analysisForm);", "setAnalysisButtonLoading(true);", "Analysis upload files must be captured in FormData before file inputs are disabled for loading.");

console.log(JSON.stringify({
  ok: true,
  checked: [
    "viewport-meta",
    "responsive-breakpoints",
    "mobile-section-title",
    "tap-target-height",
    "button-text-wrapping",
    "table-overflow",
    "key-view-markers",
    "analysis-loading-markers",
    "blank-template-download-markers",
    "screener-beginner-tooltip-markers",
    "default-all-stock-view-markers",
    "recommended-actions-control-markers",
    "portfolio-visual-filter-markers",
    "recommended-actions-initialization-order",
    "portfolio-empty-market-data-warning",
    "reference-master-launch-evidence-markers",
    "database-mode-advisor-markers",
    "production-environment-advisor-markers",
    "portfolio-health-control-markers",
    "system-admin-management-markers",
    "admin-user-delete-markers",
    "anonymous-analysis-action-lock-markers",
    "analysis-upload-formdata-before-disable",
  ],
}, null, 2));

function assertIncludes(text, expectedParts, message) {
  const missing = expectedParts.filter((part) => !text.includes(part));
  if (missing.length) {
    throw new Error(`${message}\nMissing: ${missing.join(", ")}`);
  }
}

function assertBefore(text, beforePart, afterPart, message) {
  const beforeIndex = text.indexOf(beforePart);
  const afterIndex = text.indexOf(afterPart);
  if (beforeIndex === -1 || afterIndex === -1 || beforeIndex > afterIndex) {
    throw new Error(`${message}\nExpected "${beforePart}" before "${afterPart}".`);
  }
}
